export const appointments = [
  {
    id: '1',
    patient: '1',
    doctor: 'Dr. Sarah Johnson',
    date: new Date('2024-04-15'),
    time: '10:00 AM',
    type: 'video',
    status: 'scheduled',
    reason: 'Follow-up Consultation',
    location: 'Virtual Meeting',
    notes: 'Please prepare your recent test results',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    patient: '1',
    doctor: 'Dr. Michael Chen',
    date: new Date('2024-04-20'),
    time: '2:30 PM',
    type: 'in-person',
    status: 'scheduled',
    reason: 'Annual Physical Examination',
    location: 'Main Clinic, Room 302',
    notes: 'Please arrive 15 minutes early',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    patient: '1',
    doctor: 'Dr. Emily Brown',
    date: new Date('2024-04-25'),
    time: '11:00 AM',
    type: 'phone',
    status: 'scheduled',
    reason: 'Medication Review',
    location: 'Phone Consultation',
    notes: 'Have your current medications list ready',
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]; 