export const medicines = [
  {
    id: '1',
    name: 'Lisinopril',
    genericName: 'Lisinopril',
    description: 'Used to treat high blood pressure and heart failure.',
    category: 'Antihypertensive',
    availableForms: [
      {
        form: 'Tablet',
        strengths: ['5mg', '10mg', '20mg', '40mg'],
      },
    ],
    sideEffects: ['Dizziness', 'Cough', 'Headache'],
    contraindications: ['Pregnancy', 'Angioedema'],
    interactions: ['Potassium supplements', 'Lithium'],
    storageInstructions: 'Store at room temperature.',
    manufacturer: 'Pfizer',
    barcode: '123456789',
    isPrescriptionRequired: true,
    availableStock: 100,
    usageInstructions: 'Take once daily with or without food.',
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-03-20T00:00:00Z',
  },
  {
    id: '2',
    name: 'Metformin',
    genericName: 'Metformin',
    description: 'Used to treat type 2 diabetes.',
    category: 'Antidiabetic',
    availableForms: [
      {
        form: 'Tablet',
        strengths: ['500mg', '850mg', '1000mg'],
      },
    ],
    sideEffects: ['Nausea', 'Diarrhea', 'Stomach upset'],
    contraindications: ['Kidney disease', 'Heart failure'],
    interactions: ['Alcohol', 'Contrast dye'],
    storageInstructions: 'Store at room temperature.',
    manufacturer: 'Merck',
    barcode: '987654321',
    isPrescriptionRequired: true,
    availableStock: 150,
    usageInstructions: 'Take with meals to reduce stomach upset.',
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-03-20T00:00:00Z',
  },
  {
    id: '3',
    name: 'Hydrocortisone Cream',
    genericName: 'Hydrocortisone',
    description: 'Used to treat skin conditions like eczema and dermatitis.',
    category: 'Corticosteroid',
    availableForms: [
      {
        form: 'Cream',
        strengths: ['0.5%', '1%', '2.5%'],
      },
    ],
    sideEffects: ['Skin thinning', 'Burning', 'Itching'],
    contraindications: ['Skin infections', 'Open wounds'],
    interactions: ['Other topical medications'],
    storageInstructions: 'Store at room temperature.',
    manufacturer: 'Johnson & Johnson',
    barcode: '456789123',
    isPrescriptionRequired: false,
    availableStock: 75,
    usageInstructions: 'Apply to affected area 2-4 times daily.',
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-03-20T00:00:00Z',
  },
  {
    id: '4',
    name: 'Amoxicillin',
    genericName: 'Amoxicillin',
    description: 'Used to treat bacterial infections.',
    category: 'Antibiotic',
    availableForms: [
      {
        form: 'Capsule',
        strengths: ['250mg', '500mg'],
      },
      {
        form: 'Suspension',
        strengths: ['125mg/5ml', '250mg/5ml'],
      }
    ],
    sideEffects: ['Nausea', 'Diarrhea', 'Rash'],
    contraindications: ['Penicillin allergy'],
    interactions: ['Birth control pills', 'Warfarin'],
    storageInstructions: 'Store at room temperature.',
    manufacturer: 'GlaxoSmithKline',
    barcode: '789123456',
    isPrescriptionRequired: true,
    availableStock: 200,
    usageInstructions: 'Take as directed, usually 2-3 times daily.',
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-03-20T00:00:00Z',
  }
]; 