export const pharmacists = [
  {
    id: '1',
    user: {
      id: '7',
      firstName: 'John',
      lastName: 'Smith',
      name: 'John Smith',
      email: 'john.smith@example.com',
      phoneNumber: '5551234567',
      age: 40,
      address: '123 Pharmacy St',
      profileImage: '/pharmacists/pharmacist1.jpg',
      gender: 'male',
      isActive: true,
      role: 'pharmacist',
      isVerified: true,
      lastLogin: '2024-03-20T15:30:00Z',
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-03-20T15:30:00Z',
    },
    licenseNumber: 'PH123456',
    pharmacyName: 'City Pharmacy',
    yearsOfExperience: 8,
    qualifications: ['PharmD', 'BCPS'],
    professionalBio: 'Experienced pharmacist with a focus on patient care and medication therapy management.',
    education: [
      {
        degree: 'PharmD',
        institution: 'University of California',
        year: 2016
      }
    ],
    languages: ['English', 'French'],
    specialties: ['Compounding', 'Medication Therapy Management'],
    workingHours: [
      {
        day: 'Monday',
        startTime: '08:00',
        endTime: '18:00',
        isClosed: false,
      },
      {
        day: 'Tuesday',
        startTime: '08:00',
        endTime: '18:00',
        isClosed: false,
      },
      {
        day: 'Wednesday',
        startTime: '08:00',
        endTime: '18:00',
        isClosed: false,
      },
      {
        day: 'Thursday',
        startTime: '08:00',
        endTime: '18:00',
        isClosed: false,
      },
      {
        day: 'Friday',
        startTime: '08:00',
        endTime: '18:00',
        isClosed: false,
      },
      {
        day: 'Saturday',
        startTime: '09:00',
        endTime: '17:00',
        isClosed: false,
      },
      {
        day: 'Sunday',
        startTime: '10:00',
        endTime: '16:00',
        isClosed: true,
      },
    ],
    status: 'active',
    rating: 4.7,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-03-20T15:30:00Z',
  },
  {
    id: '2',
    user: {
      id: '8',
      firstName: 'Maria',
      lastName: 'Garcia',
      name: 'Maria Garcia',
      email: 'maria.garcia@example.com',
      phoneNumber: '5559876543',
      age: 35,
      address: '456 Pharmacy Ave',
      profileImage: '/pharmacists/pharmacist2.jpg',
      gender: 'female',
      isActive: true,
      role: 'pharmacist',
      isVerified: true,
      lastLogin: '2024-03-20T14:30:00Z',
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-03-20T14:30:00Z',
    },
    licenseNumber: 'PH789012',
    pharmacyName: 'Health Plus Pharmacy',
    yearsOfExperience: 10,
    qualifications: ['PharmD', 'BCACP'],
    professionalBio: 'Specialized in geriatric care and immunizations.',
    education: [
      {
        degree: 'PharmD',
        institution: 'University of Texas',
        year: 2014
      }
    ],
    languages: ['English', 'Spanish'],
    specialties: ['Geriatric Care', 'Immunizations'],
    workingHours: [
      {
        day: 'Monday',
        startTime: '09:00',
        endTime: '19:00',
        isClosed: false,
      },
      {
        day: 'Tuesday',
        startTime: '09:00',
        endTime: '19:00',
        isClosed: false,
      },
      {
        day: 'Wednesday',
        startTime: '09:00',
        endTime: '19:00',
        isClosed: false,
      },
      {
        day: 'Thursday',
        startTime: '09:00',
        endTime: '19:00',
        isClosed: false,
      },
      {
        day: 'Friday',
        startTime: '09:00',
        endTime: '19:00',
        isClosed: false,
      },
      {
        day: 'Saturday',
        startTime: '10:00',
        endTime: '16:00',
        isClosed: false,
      },
      {
        day: 'Sunday',
        startTime: '10:00',
        endTime: '16:00',
        isClosed: true,
      },
    ],
    status: 'active',
    rating: 4.9,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-03-20T14:30:00Z',
  }
]; 