export const pharmacists = [
  {
    id: '1',
    user: {
      id: '5',
      firstName: 'Pharmacist',
      lastName: 'User',
      email: 'pharmacist@example.com',
      phoneNumber: '5551234567',
      age: 40,
      address: '123 Pharmacy St',
      profileImage: '',
      gender: 'male',
      isActive: true,
      role: 'pharmacist',
      isVerified: true,
      lastLogin: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    licenseNumber: 'PH123456',
    pharmacyName: 'CVS Pharmacy',
    yearsOfExperience: 15,
    qualifications: ['PharmD', 'BCPS'],
    professionalBio: 'Experienced pharmacist with a focus on patient care.',
    workingHours: [
      {
        day: 'Monday',
        startTime: '09:00',
        endTime: '17:00',
        isClosed: false,
      },
      {
        day: 'Tuesday',
        startTime: '09:00',
        endTime: '17:00',
        isClosed: false,
      },
      {
        day: 'Wednesday',
        startTime: '09:00',
        endTime: '17:00',
        isClosed: false,
      },
      {
        day: 'Thursday',
        startTime: '09:00',
        endTime: '17:00',
        isClosed: false,
      },
      {
        day: 'Friday',
        startTime: '09:00',
        endTime: '17:00',
        isClosed: false,
      },
      {
        day: 'Saturday',
        startTime: '10:00',
        endTime: '14:00',
        isClosed: false,
      },
      {
        day: 'Sunday',
        startTime: '10:00',
        endTime: '14:00',
        isClosed: true,
      },
    ],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]; 