export const users = [
  {
    id: '1',
    firstName: 'Admin',
    lastName: 'User',
    email: 'admin@example.com',
    password: 'password',
    phoneNumber: '1234567890',
    age: 30,
    address: '123 Admin St',
    profileImage: '',
    gender: 'male',
    isActive: true,
    role: 'admin',
    isVerified: true,
    lastLogin: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    firstName: 'Doctor',
    lastName: 'User',
    email: 'doctor@example.com',
    password: 'password',
    phoneNumber: '0987654321',
    age: 35,
    address: '456 Doctor St',
    profileImage: '',
    gender: 'female',
    isActive: true,
    role: 'doctor',
    isVerified: true,
    lastLogin: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    username: 'patient',
    password: 'password',
    role: 'patient',
    email: 'patient@example.com',
    firstName: 'Patient',
    lastName: 'User',
    createdAt: '2023-01-01T00:00:00.000Z',
    updatedAt: '2023-01-01T00:00:00.000Z',
  },
]; 